### PR TITLE
FIX #323: Check for duplicated types compile time

### LINKED ISSUE #323: Duplicated struct not identified at compile time
When a module contains two identically named structures, as in
```golo
module Test

struct Toto = { x }
  
struct Toto = { x, y }

function main = |args| {
  let t2 = Toto(1, 2)
}
```
the code compile without complaining, but fail at runtime, with `java.lang.ClassFormatError: Duplicate method name&signature` when `golo run` and with  `java.lang.LinkageError: loader (instance of GoloClassLoader): attempted duplicate class definition` when `golo golo`.

*Intended behavior*: should fail at *compile time* with explicit error, e.g.
```
[err] Duplicated `struct` definition  for "Toto" at line 5, column 1
```

### PR DESCRIPTION
**Pull request by yloiseau**
When two types (`struct` or `union`) with the same name were declared in
the same module, the code compiled without error, but an obscure
exception was raised at runtime

The case is now checked when building the IR, so that we have a clear
compiling error.

This fix the #323 issue.

### CODE REVIEW

File: src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java [hunk 1]
```diff
@@ -135,6 +135,20 @@ public void addStruct(Struct struct) {
     struct.setModuleName(getPackageAndClass());
   }
 
+  public GoloElement getSubtypeByName(String name) {
```
Comment (jponge) [inline src/main/java/org/eclipse/golo/compiler/ir/GoloModule.java]: I'm surprised you did not use the Java stream API :trollface: 

Anyway you are right, this exists early without creating intermediate objects :+1:

**Comment by jponge** [comment]
Looks good to me!
